"""empty message

Revision ID: 42b58338613e
Revises: 
Create Date: 2024-07-31 11:29:35.643271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b58338613e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pass_h', sa.String(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('ban_end', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('ext', sa.String(), nullable=True),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_ext'), ['ext'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_mime'), ['mime'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_name'), ['name'], unique=True)

    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_url_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_url_ext'), ['ext'], unique=True)
        batch_op.create_index(batch_op.f('ix_short_url_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_url_url'))
        batch_op.drop_index(batch_op.f('ix_short_url_ext'))
        batch_op.drop_index(batch_op.f('ix_short_url_domain'))

    op.drop_table('short_url')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_name'))
        batch_op.drop_index(batch_op.f('ix_files_mime'))
        batch_op.drop_index(batch_op.f('ix_files_ext'))
        batch_op.drop_index(batch_op.f('ix_files_domain'))

    op.drop_table('files')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
