"""Use int instead of datetime

Revision ID: 6c3029d9d24e
Revises: 42b58338613e
Create Date: 2024-08-07 20:52:26.397746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3029d9d24e'
down_revision = '42b58338613e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('expiry',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('expiry',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ban_end',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('last_used',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_used',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('ban_end',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.alter_column('expiry',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('expiry',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
