"""ext should NOT be a unique field lmao

Revision ID: b68b8fb2fde4
Revises: 6c3029d9d24e
Create Date: 2024-08-07 20:58:36.281798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68b8fb2fde4'
down_revision = '6c3029d9d24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_ext')
        batch_op.create_index(batch_op.f('ix_files_ext'), ['ext'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_ext'))
        batch_op.create_index('ix_files_ext', ['ext'], unique=1)

    # ### end Alembic commands ###
